CREATE TABLE availabilities (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	from_airport varchar(32) NOT NULL,
	to_airport varchar(32) NOT NULL,
	last_date date NOT NULL,
	inserted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT availabilities_unique UNIQUE (from_airport, to_airport, last_date)
);


CREATE TABLE notifications (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	topic varchar(255) NOT NULL,
	script_name varchar(255) NOT NULL,
	message text NOT NULL,
	inserted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	CONSTRAINT notifications_unique UNIQUE (topic, message, script_name)
);

CREATE TABLE destinations (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	from_airport varchar(32) NOT NULL,
	to_airport varchar(32) NOT NULL,
	is_active boolean NOT NULL DEFAULT true,
	inserted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
	CONSTRAINT destinations_unique UNIQUE (from_airport, to_airport)
);
