CREATE TABLE availabilities (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	from_airport varchar(32) NOT NULL,
	to_airport varchar(32) NOT NULL,
	last_date date NOT NULL,
	inserted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT availabilities_unique UNIQUE (from_airport, to_airport, last_date)
);
